server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${variable.postgres}:5433/transacaodb
    username: postgres
    password: postgres
  jpa:
    database-platform: postgres
    generate-ddl: true

    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

variable:
  postgres: localhost